### ISSUE TITLE
Roider sets all damage dealt equal to crowbar damage while crowbar is held

### ISSUE THREAD

**Issue by The1337Gh0st** [Kroqh/ttt-role_roider#1]
When holding out the crowbar, all damage you deal is set to deal damage equal to your crowbar damage. This can have an unintended interaction with certain items, as it can cause them to deal more or less damage than intended. 
For example, throwing an incendiary grenade causes it to deal your crowbar damage every time it deals damage. Dying to your own incendiary grenade also causes the following Lua error:
[[TTT2] Roider [ROLE]] lua/terrortown/autorun/server/sv_roider_handler.lua:15: Tried to use a NULL entity!
    1. GetClass - [C]:-1
        2. fn - lua/terrortown/autorun/server/sv_roider_handler.lua:15
            3. Run - lua/ulib/shared/hook.lua:109
                4. unknown - gamemodes/terrortown/gamemode/server/sv_player.lua:1116
                    5. TakeDamageInfo - [C]:-1
                        6. RadiusDamage - gamemodes/terrortown/entities/entities/ttt_flame.lua:109
                            7. unknown - gamemodes/terrortown/entities/entities/ttt_flame.lua:182

**Comment by Kroqh** [comment]
Thanks, it should be fixed now 😎
